### ISSUE TITLE
URL on the repo is 404

### ISSUE THREAD

**Issue by mithro** [apertus-open-source-cinema/naps#17]
The URL on this repository goes to https://apertus-open-source-cinema.github.io/nmigen-gateware/intro.html which seems to be a 404. In fact the docs at https://apertus-open-source-cinema.github.io/ seem to be non-existent?

**Comment by rroohhh** [comment]
Fixed, we renamed the repository some time ago and must have missed this link.

The correct one is https://apertus-open-source-cinema.github.io/naps/intro.html now.
